name: ml
channels:
  - defaults
dependencies:
  - ipykernel
  - isort
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyarrow
  - pylint
  - python=3.12
  - scikit-learn
  - scipy
  - tabulate
  - yapf
